### ISSUE TITLE
[refactor] Move more ViewModel functions to use cases

### ISSUE THREAD

**Issue by ryanw-mobile** [ryanw-mobile/GMap2ICal#7]
- From within use cases we can call other use cases

Further splitting viewmodel functions to use cases will help unit testing some currently private functions in a more detailed way.
The current viewModel unit test approach is not doing its best to safeguard all important scenarios. 

The interfacing viewmodel function will remain there meaning some existing unit tests might survive, but some other new unit tests will be written for the new use cases in finer detail.

**Comment by ryanwong-uk** [comment]
Has been stayed here for pretty long time and will have to check if this is still necessary - possibly not.

**Comment by ryanwong-uk** [comment]
It would incur some effort because:
- When converting certain private functions to use-cases, ViewModel will have to collect extra flows and update the UIState in the init block.
- Unit tests will have to be split into smaller tests

Eventually we won't have viewModel functions that write to mutableStates/UIState directly. It will be through collecting individual Flows from various use-cases and then compiling the UIState using a single function.

Should try but it will take some time.

**Comment by ryanw-mobile** [comment]
We have enough use cases, so closing
